 import 'package:flutter/material.dart';
import 'package:ricomusic/model/model_listview.dart';
 final List<ModelListview> musicItems = [
  ModelListview(
    title: "7 Rings",
    artist: "Ariana Grande",
    streams: "1.2 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Love Story",
    artist: "Taylor Swift",
    streams: "3 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Thank U, Next",
    artist: "Ariana Grande",
    streams: "1.8 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Shake It Off",
    artist: "Taylor Swift",
    streams: "5 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Positions",
    artist: "Ariana Grande",
    streams: "980k / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Blank Space",
    artist: "Taylor Swift",
    streams: "4 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "No Tears Left to Cry",
    artist: "Ariana Grande",
    streams: "2 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "You Belong with Me",
    artist: "Taylor Swift",
    streams: "6 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Into You",
    artist: "Ariana Grande",
    streams: "1.5 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Wildest Dreams",
    artist: "Taylor Swift",
    streams: "3.5 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Dangerous Woman",
    artist: "Ariana Grande",
    streams: "2.1 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Bad Blood",
    artist: "Taylor Swift",
    streams: "4.5 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Problem",
    artist: "Ariana Grande",
    streams: "3 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Cardigan",
    artist: "Taylor Swift",
    streams: "2 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "One Last Time",
    artist: "Ariana Grande",
    streams: "4 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Willow",
    artist: "Taylor Swift",
    streams: "1.5 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Side to Side",
    artist: "Ariana Grande",
    streams: "3.2 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Style",
    artist: "Taylor Swift",
    streams: "5 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "God Is a Woman",
    artist: "Ariana Grande",
    streams: "2.5 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Lover",
    artist: "Taylor Swift",
    streams: "3 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Breathin",
    artist: "Ariana Grande",
    streams: "1.8 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "ME!",
    artist: "Taylor Swift",
    streams: "4 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Bang Bang",
    artist: "Ariana Grande",
    streams: "3 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "The Man",
    artist: "Taylor Swift",
    streams: "1.7 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Stuck with U",
    artist: "Ariana Grande",
    streams: "2.4 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Teardrops on My Guitar",
    artist: "Taylor Swift",
    streams: "3.3 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Rain on Me",
    artist: "Ariana Grande",
    streams: "1.5 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Enchanted",
    artist: "Taylor Swift",
    streams: "2.8 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Everyday",
    artist: "Ariana Grande",
    streams: "1.2 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Back to December",
    artist: "Taylor Swift",
    streams: "2 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "The Way",
    artist: "Ariana Grande",
    streams: "3.1 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Red",
    artist: "Taylor Swift",
    streams: "3.5 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Be Alright",
    artist: "Ariana Grande",
    streams: "2 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "22",
    artist: "Taylor Swift",
    streams: "4 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Break Free",
    artist: "Ariana Grande",
    streams: "3.8 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Delicate",
    artist: "Taylor Swift",
    streams: "2.1 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Greedy",
    artist: "Ariana Grande",
    streams: "1.7 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "New Romantics",
    artist: "Taylor Swift",
    streams: "2.6 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Dangerous Woman",
    artist: "Ariana Grande",
    streams: "2 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "All Too Well",
    artist: "Taylor Swift",
    streams: "5 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "My Everything",
    artist: "Ariana Grande",
    streams: "1.9 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Our Song",
    artist: "Taylor Swift",
    streams: "3 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Sweetener",
    artist: "Ariana Grande",
    streams: "2.5 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Out of the Woods",
    artist: "Taylor Swift",
    streams: "2 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Almost Is Never Enough",
    artist: "Ariana Grande",
    streams: "1.6 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Fearless",
    artist: "Taylor Swift",
    streams: "4.1 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
  ModelListview(
    title: "Touch It",
    artist: "Ariana Grande",
    streams: "2.3 Million / streams",
    imagePath: "images/ariana.png",
  ),
  ModelListview(
    title: "Speak Now",
    artist: "Taylor Swift",
    streams: "3.8 Million / streams",
    imagePath: "images/taylor.jpg",
  ),
];


  final List<ModelListview> musicSearch = [
    ModelListview(
      title: "We Can't Be Friends",
      artist: "Taylor Swift",
      streams: "3 Million / steams",
      imagePath: "images/ariana.png",
    ),
    ModelListview(
      title: "Wildest Dreams",
      artist: "Taylor Swift",
      streams: "560.5k / steams",
      imagePath: "images/ariana.png",
    ),
    ModelListview(
      title: "I Have Nothing",
      artist: "Whitney Houston",
      streams: "960.5k / steams",
      imagePath: "images/taylor.jpg",
    ),
    ModelListview(
      title: "We Can't Be Friends",
      artist: "Taylor Swift",
      streams: "3 Million / steams",
      imagePath: "images/ariana.png",
    ),
    ModelListview(
      title: "Wildest Dreams",
      artist: "Taylor Swift",
      streams: "560.5k / steams",
      imagePath: "images/ariana.png",
    ),
    ModelListview(
      title: "I Have Nothing",
      artist: "Whitney Houston",
      streams: "960.5k / steams",
      imagePath: "images/taylor.jpg",
    ),
    ModelListview(
      title: "We Can't Be Friends",
      artist: "Taylor Swift",
      streams: "3 Million / steams",
      imagePath: "images/ariana.png",
    ),
    ModelListview(
      title: "Wildest Dreams",
      artist: "Taylor Swift",
      streams: "560.5k / steams",
      imagePath: "images/ariana.png",
    ),
    ModelListview(
      title: "I Have Nothing",
      artist: "Whitney Houston",
      streams: "960.5k / steams",
      imagePath: "images/taylor.jpg",
    ),
    ModelListview(
      title: "We Can't Be Friends",
      artist: "Taylor Swift",
      streams: "3 Million / steams",
      imagePath: "images/ariana.png",
    ),
    ModelListview(
      title: "Wildest Dreams",
      artist: "Taylor Swift",
      streams: "560.5k / steams",
      imagePath: "images/ariana.png",
    ),
    ModelListview(
      title: "I Have Nothing",
      artist: "Whitney Houston",
      streams: "960.5k / steams",
      imagePath: "images/taylor.jpg",
    ),
    
    // Add more items as needed
  ];
  final List<ModelListview> topAlbumSongs = [
    ModelListview(
      title: "How You Like That",
      artist: "Blackpink",
      streams: "100 Million / steams",
      imagePath: "images/one.png",
    ),
    ModelListview(
      title: "Radio",
      artist: "Lana del Rey",
      streams: "500 Million / steams",
      imagePath: "images/three.png",
    ),
    ModelListview(
      title: "How You Like That",
      artist: "Blackpink",
      streams: "100 Million / steams",
      imagePath: "images/one.png",
    ),
    ModelListview(
      title: "Radio",
      artist: "Lana del Rey",
      streams: "500 Million / steams",
      imagePath: "images/three.png",
    ),
    ModelListview(
      title: "How You Like That",
      artist: "Blackpink",
      streams: "100 Million / steams",
      imagePath: "images/one.png",
    ),
    ModelListview(
      title: "Radio",
      artist: "Lana del Rey",
      streams: "500 Million / steams",
      imagePath: "images/three.png",
    ),
    ModelListview(
      title: "How You Like That",
      artist: "Blackpink",
      streams: "100 Million / steams",
      imagePath: "images/one.png",
    ),
    ModelListview(
      title: "Radio",
      artist: "Lana del Rey",
      streams: "500 Million / steams",
      imagePath: "images/three.png",
    ),
    ModelListview(
      title: "How You Like That",
      artist: "Blackpink",
      streams: "100 Million / steams",
      imagePath: "images/one.png",
    ),
    ModelListview(
      title: "Radio",
      artist: "Lana del Rey",
      streams: "500 Million / steams",
      imagePath: "images/three.png",
    ),
    ModelListview(
      title: "How You Like That",
      artist: "Blackpink",
      streams: "100 Million / steams",
      imagePath: "images/one.png",
    ),
    ModelListview(
      title: "Radio",
      artist: "Lana del Rey",
      streams: "500 Million / steams",
      imagePath: "images/three.png",
    ),
    
    
    // Add more items as needed
  ];